version: '3'

services:
  sparkifycassandra:
    build:
      context: .
      dockerfile: ./compose/cassandra/Dockerfile
    image: cassandra
    container_name: cassandradb
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    # volumes:
      # - ./cassandra_data:/var/lib/cassandra

  jupyter_notebook:
    build:
      context: .
      dockerfile: ./compose/jupyter-notebook/Dockerfile
    image: cassandra_jupyter_notebook
    container_name: cassandra_jupyter_notebook
    volumes:
      - type: "bind"
        source: "./workspace"
        target: "/home/jovyan/src"
    ports:
      - "8888:8888"
